#  Build & Run FHIR Publisher, and push output to gh-pages

langauge: java
jdk:
  - oraclejdk7
script: true
#./build.sh
after_success: 
  - echo -e "MIIEowIBAAKCAQEAq/ZDzg390C6bZiWMD4K0piafMW3GixQwZQn4g/bP49y/f5Eufay/yuDiCx0rUdQEIOWT1RaeLklMof1CGT3wgahf89wncp8sDe/hNb/nQLcdHR46m3fbvgcZbCOR69Q8q8Ao1QVPgOt62QVne6oOL70N8CVJjZdjXOzI1xBn+RBsyxk68Jc1+xHiEvAKOkLNMjVsXg7Cx18hi4+2oIc51jkyr5wLdyyJvS+nfm+XNrk2bCLd8Jk9KCWMzG3C2GtKbOGnuHde6694P+2qP/aSJu+JUgtg1kA5TsKy5E82IOviLWFOys5Ll58r0fDWE4Ai4by3kCOOzOaDH43p36nvVQIDAQABAoIBAQChWdgzXpN6JFExnid2YkkI4ZJbucois5XZKGrjv9E+1+FjXCFIULBBN5NBpGQCSrJ4/5EfzzIq8iISmOTNdH3X2tn1oevttAaNKTiiy2a8JVUO/k81k1g/TMAA5LtFkYZADXUCtBHuQIWrXlPECEN5baXHX+VNEvBrv82PZlh4q/P3H4dIPJpHXVFbuNC8pXSc0RcArmfbmDt+nTqES19XxlqlPJYItsEWN74bvXGuxJH1FTkLf1bC2J7LfeBQBc5q1YnVUnrZIfFkwpDJRxO32EUT10H631Lp/FCNxB0oW+W+KuBzlYQzo5CCXA3nlBAPivGvL9y/7433TtuzI9+9AoGBANOobwopDbCu3CveyzcLa/2VjPQwtrR+4SMHUgTGYFAF3IWiTsAF/21OVMnzYZsCHHY2x8PKX2A2At01FUIyETDKg+Q3z458X0tuyQd9mE+u/VpgWPkBqoA0cDZoyu3HwmQDgBrxNQnXnPMT74tk3IqlNBro1XII0x3utLJMT+w3AoGBAM/83s9kwqghWkXkXsoo32PXXfSO66wK/IwTArp3sQqhfb/3bZyMz8R1gy1cHRhq9L8z0JVnChL08aiq43iR2BojtHLZA/eizY9/7yV0m0+oUR1DWZ3DM+d3OGTegwrWPc/3vtAeEJJL7BtVpZphsnzMnQ5L75LHB8Bmc/eG1LLTAoGAYFyFuT15kx/48ywqnrPfhYLpul7XP5OoUjdJ+wyJ2sTgYiLD8Z6JbK1F4u+gV179sEA+cIAZLgdJBIbfV9TNiMYah/N01mz/Qat9cKCYkGadx+CngS5l/pphIBRTly/j637AewOn3wQ/21cPLwpLcf/Gmh2414L3AuCjea1Okb8CgYAmhWUW8EiFLzgy/ar4sj09lqPWKapIgPhpURQOSSDHIUXTChaJCiNo9YLIIelZnmWaDBSztxPMkwU3Af+DUy+9F6PSKZNsiACedUlrnH8vb7MmQlUUvRSd6BzPwc5vcWKdY/s5PHhBQEKIhYJYZ4PRTWxBO5sxih9LaS5NR/GY9QKBgBNQ6PWRWE5m0jh7izZrzrRF2RsyebW5KhJ3jP8gkwYSRmVZlQnBngXiN3yeCjDJ2bAQRIpS6Pn0ZcTD3EuUG2Eo+niSn92C3ZMyq0Yvf+GaELdYDMm6uqhKzDBLHUoTHzIJoTgMBxUVqF1925/LC98Se+xm/vLworsC3Z22tIgi\n" > ~/.ssh/id_rsa
  - echo -e "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCr9kPODf3QLptmJYwPgrSmJp8xbcaLFDBlCfiD9s/j3L9/kS59rL/K4OILHStR1AQg5ZPVFp4uSUyh/UIZPfCBqF/z3CdynywN7+E1v+dAtx0dHjqbd9u+BxlsI5Hr1DyrwCjVBU+A63rZBWd7qg4vvQ3wJUmNl2Nc7MjXEGf5EGzLGTrwlzX7EeIS8Ao6Qs0yNWxeDsLHXyGLj7aghznWOTKvnAt3LIm9L6d+b5c2uTZsIt3wmT0oJYzMbcLYa0ps4ae4d17rr3g/7ao/9pIm74lSC2DWQDlOwrLkTzYg6+ItYU7KzkuXnyvR8NYTgCLhvLeQI47M5oMfjenfqe9V serzh@serzh-System-Product-Name" > ~/.ssh/id_rsa.pub
  - chmod 600 ~/deploy_fhir_docs
  - git config --global user.email "latest@fhir.me"
  - git config --global user.name "FHIR Build"
  - echo -e "Host github.com\n  IdentityFile ~/deploy_fhir_docs" > ~/.ssh/config
  - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts
  - mkdir hl7-fhir.github.io
  - cd hl7-fhir.github.io
  - git init
  - git remote add origin git@github.com:fhir-ru/fhir-ru.github.io
  - touch .test
#  - cp -r ../publish/* .
  - git add -A .
  - git commit -m "Travis docs build"
  - git push -f origin master


env:
  global:
    secure: "MV6r5LHUxQns93+NuKCv+iJPDLoSRSXpJ5YNq36mlO7pKIiHxWOYkrdxaXFyZU7lJzYMuJuFFpPPmzBNN8AqGo+3GY/ge6cODbYyAyS+PPUnazKNSyha7Hu9XQh1px44NBgnwE3wbltXYYvwQbHe8vXhDwBLXYZe9xj0g4YY4ms="

# To recreate the payload + "secure" var above:
# password=`openssl rand -hex 32`
# cat ~/.ssh/deploy_fhir_docs | openssl aes-256-cbc -k "$password" -a 
# travis encrypt password=$password -r hl7-fhir/fhir-svn
