# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish generated content to GitHub Pages
      shell: bash
      run: |
        echo "Will publish!"       
        PASSPHRASE=$(DEPLOY_KEY_PASSPHRASE)       
        echo $(DEPLOY_KEY_ENCRYPTED) | openssl  enc -aes-256-cbc -d  -pass pass:$PASSPHRASE  -base64 -A > ${BUILD_REPOSITORY_LOCALPATH}/deploy.rsa
        chmod 400 ${BUILD_REPOSITORY_LOCALPATH}/deploy.rsa       
        ls -l ${BUILD_REPOSITORY_LOCALPATH}/deploy.rsa
        wc ${BUILD_REPOSITORY_LOCALPATH}/deploy.rsa
        git init
        git config user.email "gh-actions-build@fhir.org"
        git config user.name "GH Actions Builder"
        git remote add origin git@github.com:fhir-ru/fhir-ru.github.io
        touch .test
        ../remove_files_larger_than_100mg_for_gh_pages_compatibility.sh
        git add -A .
        git commit -m "GH Actions docs build"       
        ssh -i ${BUILD_REPOSITORY_LOCALPATH}/deploy.rsa git@github.com
        GIT_SSH_COMMAND='ssh -i ${BUILD_REPOSITORY_LOCALPATH}/deploy.rsa' git push -f origin master
        rm ${BUILD_REPOSITORY_LOCALPATH}/deploy.rsa
        workingDirectory: publish
