# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - shell: bash
      run: |
        cp -R source.ru/* source
        set -ev
        git fetch --depth 20
        [ -d publish ] && rm -rf publish
        NAME="Непрерывная интеграционная сборка"
        SVNREV=$(git rev-parse --short HEAD)
        antBuild (){
         ant -Dargs="./publish.sh -svn $SVNREV -name \'$NAME\' -url http://build.fhir.org/  -post-pr"
           checkStatus
        }
        checkStatus (){
         nf=`find publish -maxdepth 1 -type f | wc -l`
         if [ "$nf" -lt "100" ] ; then
            echo "< 100 files produced: bailing!"
            exit 1
         fi
         if [ $? -eq 0 -a ! -f fhir-error-dump.txt ]
         then
           echo "Build status OK"
         else
           echo "error dump:"
           cat fhir-error-dump.txt
           exit 1
         fi
        }
        antBuild
        displayName: 'Build via build.sh'
    - shell: bash
      run: |
        echo "Will publish!"
        touch .test
        ../remove_files_larger_than_100mg_for_gh_pages_compatibility.sh
    - name: publish
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: publish fhir-ru fhir-ru.github.io
